In [2]:
import numpy as np
a = np.array([[23,45,67,86] , [23,45,56,78]])
a.ndim
# accessing element in 2Dimension : first number(1) in c[1,2] access which 
#array and 2nd number(2) which
# element in array which is 56 
a[1 , 2]
# print(a)

56

In [34]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b.ndim
b[2,2]
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]] , [[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]]] )
c.ndim
# accessing element in 3Dimension : first number(1) in c[1,0,2] access which 
# 2d array , 2nd number(0) which array in 2d array and 3rd number(2) which
# element in array which is -3

# c[1,0,2]
# type(c)
c.shape[2]
c.size
c.nbytes


72

In [89]:
# d = np.arange(10)
# print(d)

e=np.random.permutation(np.arange(10))#np.random.permutation:shuffle element randomly
# print(e)

np.random.randint(20,30) #np.random.randint: randomly select integer btw 20 & 30.

f = np.arange(20).reshape(4,5)
print(f)
# print(list(range(3,34,3)))
# a = np.array([23,3,4,34])
# c = np.full_like(a,5,)
# print(c)
# print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [30]:
import numpy as np
h = np.arange(10) 
i = np.random.permutation(h / 2.5 * 1.5)
print(i)


[1.2 4.2 0.  5.4 0.6 1.8 3.6 2.4 4.8 3. ]


In [22]:
j = np.random.rand(2,3,4,2)
j.ndim

h = np.arange(100).reshape(10,10) #reshape e
h

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

Slicing and indexing in Numpy

In [59]:
A = np.arange(100)
B = A[:20].copy()
B[0] = 200
# print(B)
# print(A)

A[::-1] ## reversing the array


## Finding index and changing its value
idx = np.argwhere(B == 200)[0][0]
idx
B[idx] = 0   
B 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [87]:
C = np.round(10 * np.random.rand(5,4))
C[1,2] ## accessing an element 1 is for row 2 is for column in that row

C[1,:] ##accessing whole row with all element in that row

C[:,1] ##accessing whole column with all element in that column

C[1:3,2:4] ##it create submatrix,from row 1 and 2,select ele in 2 and 3 column

C.sort(axis = 0) ## sort each column ascendingly
print(C)
C.sort(axis = 1) ## sort each row ascendingly
print(C)

[[ 0.  1.  3.  3.]
 [ 5.  1.  7.  4.]
 [ 5.  7.  9.  6.]
 [ 6.  9.  9.  6.]
 [ 7.  9. 10.  7.]]
[[ 0.  1.  3.  3.]
 [ 1.  4.  5.  7.]
 [ 5.  6.  7.  9.]
 [ 6.  6.  9.  9.]
 [ 7.  7.  9. 10.]]


In [103]:
k = np.arange(100)
k[(k%2 != 0) & (k%3 == 0)]

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99])

In [3]:
import numpy as np
# BroadCasting :  adding something to ndimension array
A = np.round(10 * np.random.rand(2,3))
A + 3
A+(np.arange(2).reshape(2,1))

# np.hstack :  concatenate array horizentally
# np.vstack :  concatenate array vertically
B = np.round(10 * np.random.rand(2,2))
C = np.hstack((A,B))
C

# np.sort : sorting array
A = np.random.permutation(np.arange(10))
A
A.sort()
d= A[::-1] ## sorting in reverse order
print(d)

S = np.array(["Hello" , "Are" , "You" , " Alright"])
S.sort() ## sort in alpabetic order.
S

[9 8 7 6 5 4 3 2 1 0]


array([' Alright', 'Are', 'Hello', 'You'], dtype='<U8')

In [ ]:
b = np.random.rand(100000)
%timeit np.sum(b)
%timeit sum(b)

def summ(G):
    s = 0 
    for x in G:
        s+=x
    return s
%timeit summ(b)


In [1]:
b = np.array([
              [1,2,3,11],
              [4,5,6,44],
              [7,8,9,77],
              [41,51,61,55],
              [72,82,92,99]])
b[3:,:2]

A = np.array(
[ [ [45, 12, 4], [45, 13, 5], [46, 12, 6] ],
[ [46, 14, 4], [45, 14, 5], [46, 11, 5] ],
[ [47, 13, 2], [48, 15, 5], [52, 15, 1] ] ])

A[1:3 , 2:]
c = np.arange(36).reshape(3,4,3)
c

NameError: name 'np' is not defined

In [11]:
kanto = np.array([3,4,5])
(kanto * weight).sum()
weight =  np.array([8,9,7])
np.dot(kanto , weight)

95

In [27]:
%%time
arr1 = list(range(100000))
arr2 = list(range(100000 , 200000))

ar1 = np.array(arr1)
ar2 = np.array(arr2)


result = 0

for x1,x2 in zip(ar1,ar2):
    result += x1 * x2
result


# 

CPU times: total: 422 ms
Wall time: 461 ms


<timed exec>:11: RuntimeWarning: overflow encountered in scalar add
<timed exec>:11: RuntimeWarning: overflow encountered in scalar multiply


893678192

In [35]:
%time
np.dot(ar1, ar2)

CPU times: total: 0 ns
Wall time: 0 ns


893678192

In [38]:
## np.ones([2,3,4])
np.zeros((3,4,5))
np.eye(3) ##identity matrix
np.random.rand(2,2, 3)##random matrix
np.random.randn(1,2,3) ##value btw 1 and -1
np.full([2,3],42)##fixed value
np.arange(10,90,3)##raange with start, stop ,step
np.linspace(2,32,4)##equally space numbers in a range
mu = np.arange(10,90,3).reshape(3,3,3)
np.divide( mu ,3)
np.multiply( mu ,4)
np.multiply( mu ,5)
np.sum(mu)


1323

In [46]:
import os
os.getcwd()
os.listdir('C:\\Users\\Hp\\Python')

'Data' in os.listdir('C:\\Users\\Hp\\Python')

True